using MusicHub.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MusicHub.Models.LocalModels
{
    /// <summary>
    /// A user model.
    /// The Email address is the key of this model.
    /// </summary>
    public class UserModel : IUser
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]//Specifies that primary key values are provided by the user rather than generated by the database.
        [Key]
        public string EmailAddress { get; set; }

        #region Properties

        /// <summary>
        /// User's first name.
        /// </summary>
        [StringLength(30, ErrorMessage = "First name cannot be longer than 30 characters.")]
        public string Name { get; set; }
        /// <summary>
        /// User's last name.
        /// </summary>
        [StringLength(30, ErrorMessage = "Last name cannot be longer than 30 characters.")]
        public string LastName { get; set; }
        /// <summary>
        /// User birth date.
        /// </summary>
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }
        /// <summary>
        /// The songs id's playlist of a specific user.
        /// </summary>
        public List<SongModel> Playlist { get; set; }

        #endregion

        /// <summary>
        /// Initialize model.
        /// </summary>
        public UserModel()
        {
            //Playlist = new List<int>();
        }
    }
}
